export const GENDERS = [
  { id: 1, name: 'Hip-Hop' },
  { id: 2, name: 'Rap' },
  { id: 3, name: 'Pop' },
  { id: 4, name: 'Rock' },
  { id: 5, name: 'Metal' },
  { id: 6, name: 'Punk' },
  { id: 7, name: 'Jazz' },
  { id: 8, name: 'Country' },
  { id: 9, name: 'Folk' },
  { id: 10, name: 'Classical' },
  { id: 11, name: 'Electronic' },
  { id: 12, name: 'Reggae' },
  { id: 13, name: 'R&B' },
  { id: 14, name: 'Disco' },
  { id: 15, name: 'Techno' },
  { id: 16, name: 'Dance' },
  { id: 17, name: 'House' },
  { id: 18, name: 'Indie' },
  { id: 19, name: 'Alternative' },
  { id: 20, name: 'Instrumental' },
  { id: 21, name: 'Soundtrack' },
  { id: 22, name: 'Latin' },
];
